(define make-state list)
(define xpos car)
(define ypos cadr)
(define heading caddr)

(define (interpret word state d a)
  (define plane (js-new (js-eval "Plane") "A Plane" 500 500))
  (define turtle
    (js-invoke plane "createTurtle" (xpos state) (ypos state) (heading state)))
  (define (dispatch m)
    (cond ((eq? m 'F) (js-invoke turtle "forward" d))
          ((eq? m '+) (js-invoke turtle "turnRight" a))
          ((eq? m '-) (js-invoke turtle "turnLeft" a))
          (else (error "Unknown alphabet"))))
  (for-each dispatch word))
